spring.application.name=SPRING_HOMEWORK_003
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/homework_003
spring.datasource.username=sovannarith
spring.datasource.password=1111
